
(()=>{'use strict';
const M=window.FOSELEV_MACHINES||[],KEY='foselev_vfg_visits',CONTROLLERS_KEY='foselev_vfg_controllers',CHECKS=['Identification et documents','État général / carrosserie','Pneumatiques et essieux','Moteur et transmission','Hydraulique et flexibles','Sécurités et signalisation','Structure / châssis / stabilisateurs','Essai fonctionnel'];
const S={machine:null,deferred:null};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const norm=v=>String(v??'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().trim();
function visits(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}function put(v){localStorage.setItem(KEY,JSON.stringify(v))}
function savedControllers(){try{return JSON.parse(localStorage.getItem(CONTROLLERS_KEY)||'[]')}catch{return[]}}
function controllers(){let map=new Map;savedControllers().forEach(c=>{if(c&&c.name)map.set(norm(c.name),{name:c.name,phone:c.phone||''})});visits().forEach(v=>{if(v.technician){let k=norm(v.technician),cur=map.get(k)||{name:v.technician,phone:''};if(v.technicianPhone)cur.phone=v.technicianPhone;map.set(k,cur)}});return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'fr'))}
function saveController(name,phone){name=(name||'').trim();phone=(phone||'').trim();if(!name)return;let list=controllers(),k=norm(name),i=list.findIndex(c=>norm(c.name)===k);if(i>=0)list[i]={name,phone:phone||list[i].phone||''};else list.push({name,phone});localStorage.setItem(CONTROLLERS_KEY,JSON.stringify(list));renderControllerSuggestions()}
function renderControllerSuggestions(){let list=controllers(),dl=$('#controllerList');if(dl)dl.innerHTML=list.map(c=>`<option value="${esc(c.name)}">${esc(c.phone||'')}</option>`).join('')}
function autofillController(){let c=controllers().find(x=>norm(x.name)===norm($('#tech').value));if(c&&c.phone)$('#techPhone').value=c.phone}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function screen(n){$$('.screen').forEach(x=>x.classList.toggle('active',x.id==='s-'+n));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===n||(n==='machine'&&x.dataset.nav==='search')));scrollTo(0,0);if(n==='history')renderAllHistory();if(n==='machine')renderMachineHistory()}
function uniq(a){return [...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'))}function fill(){uniq(M.map(x=>x.company)).forEach(v=>$('#company').insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));agencies()}
function agencies(){let c=$('#company').value,cur=$('#agency').value,a=uniq(M.filter(x=>!c||x.company===c).map(x=>x.agency));$('#agency').innerHTML='<option value="">Toutes les agences</option>'+a.map(v=>`<option>${esc(v)}</option>`).join('');if(a.includes(cur))$('#agency').value=cur}
function filtered(){let q=norm($('#q').value),c=$('#company').value,a=$('#agency').value,cats=$$('.cat:checked').map(x=>x.value);return M.filter(x=>cats.includes(x.category)&&(!c||x.company===c)&&(!a||x.agency===a)&&(!q||norm([x.parkNumber,x.registration,x.serialNumber,x.company,x.agency,x.brand,x.model,x.designation,x.city].join(' ')).includes(q)))}
function renderResults(){let list=filtered();$('#count').textContent=list.length;$('#results').innerHTML=list.length?list.map((x,i)=>`<button class="result" data-i="${M.indexOf(x)}"><div class="row"><strong>${esc(x.parkNumber)}</strong><span class="badge">${esc(x.category)}</span></div><div class="model">${esc(x.brand)} ${esc(x.model)}</div><div class="meta">${esc(x.company)} · ${esc(x.agency)}</div></button>`).join(''):'<div class="card empty">Aucun matériel trouvé.</div>';$$('.result').forEach(b=>b.onclick=()=>openMachine(M[+b.dataset.i]))}
function fmt(v){if(!v)return'Non renseignée';let d=new Date(v+(String(v).length===10?'T12:00:00':''));return isNaN(d)?v:new Intl.DateTimeFormat('fr-FR').format(d)}function due(x){if(!x.firstRegistration)return'Non renseignée';let d=new Date(x.firstRegistration+'T12:00:00'),y=d.getFullYear(),years=x.category==='GM'&&y===2023?3:2;d.setFullYear(y+years);return fmt(d.toISOString().slice(0,10))}function info(l,v){return`<div class="info"><span>${esc(l)}</span><strong>${esc(v||'Non renseigné')}</strong></div>`}
function agencyContact(x){return (window.FOSELEV_AGENCIES||{})[x.agencyId]||null}
function contactBlock(x){let a=agencyContact(x);if(!a)return '';let addr=[a.address,[a.postalCode,a.city].filter(Boolean).join(' '),a.country&&a.country!=='FRANCE'?a.country:''].filter(Boolean).join(', ');let phone=a.phone?`<a class="contact-link" href="tel:${esc(a.phone.replace(/\s+/g,''))}">☎ ${esc(a.phone)}</a>`:'<span>Non renseigné</span>';let email=a.email?`<a class="contact-link" href="mailto:${esc(a.email)}">✉ ${esc(a.email)}</a>`:'<span>Non renseigné</span>';return`<div class="agency-contact"><h3>Coordonnées de l’agence</h3>${addr?`<div class="contact-line"><strong>Adresse</strong><span>${esc(addr)}</span></div>`:''}<div class="contact-line"><strong>Téléphone</strong>${phone}</div><div class="contact-line"><strong>E-mail</strong>${email}</div>${a.manager?`<div class="contact-line"><strong>Responsable</strong><span>${esc(a.manager)}</span></div>`:''}</div>`}
function openMachine(x){S.machine=x;$('#machineCard').innerHTML=`<div class="row machineHead"><div><div class="eyebrow" style="color:var(--navy)">${esc(x.category)}</div><h2>${esc(x.parkNumber)}</h2><strong>${esc(x.brand)} ${esc(x.model)}</strong></div><span class="badge">${esc(x.status)}</span></div><div class="infos">${info('Désignation',x.designation)}${info('Capacité',x.capacity?(x.capacity+' '+x.capacityUnit):'')}${info('Société',x.company)}${info('Agence',x.agency)}${info('Ville',x.city)}${info('Immatriculation',x.registration)}${info('N° de série',x.serialNumber)}${info('1re mise en circulation',fmt(x.firstRegistration))}${info('Échéance VFG indicative',due(x))}${info('ID agence',x.agencyId)}</div>${contactBlock(x)}`;screen('machine')}
function renderMachineHistory(){let box=$('#machineHistory');if(!S.machine){box.innerHTML='<div class="empty">Aucun matériel sélectionné.</div>';return}let v=visits().filter(x=>x.machineSnapshot.parkNumber===S.machine.parkNumber);box.innerHTML=v.length?v.map(historyHtml).join(''):'<div class="empty">Aucune visite pour ce matériel.</div>';bindHistoryActions(box)}
function startVisit(){if(!S.machine)return toast('Sélectionne un matériel.');$('#visitDate').value=new Date().toISOString().slice(0,10);renderControllerSuggestions();$('#tech').value='';$('#techPhone').value='';$('#carrierKm').value='';$('#carrierHours').value='';$('#upperHours').value='';$('#notes').value='';$('#globalStatus').value='Conforme';$('#visitSummary').innerHTML=`<strong>${esc(S.machine.parkNumber)} — ${esc(S.machine.brand)} ${esc(S.machine.model)}</strong><br><span class="meta">${esc(S.machine.company)} · ${esc(S.machine.agency)}</span>`;$('#checks').innerHTML=CHECKS.map((c,i)=>`<div class="check"><h4>${i+1}. ${esc(c)}</h4><div class="status-grid"><select class="checkStatus"><option>Conforme</option><option>Observation</option><option>Réserve</option><option>Non conforme</option><option>Non contrôlé</option></select><input class="checkComment" placeholder="Commentaire facultatif"></div></div>`).join('');screen('visit')}
function parseFrenchNumber(v){let t=String(v||'').replace(/[\s\u00a0\u202f]/g,'').replace(',','.').replace(/[^0-9.]/g,'');let parts=t.split('.');if(parts.length>2)t=parts.shift()+'.'+parts.join('');return t}
function formatFrenchNumber(v,decimals=false){let n=parseFrenchNumber(v);if(!n)return'';let x=Number(n);if(!Number.isFinite(x))return'';return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:decimals?1:0,minimumFractionDigits:0}).format(x)}
function bindNumberField(id,decimals=false){let el=$(id);el.addEventListener('focus',()=>{el.value=parseFrenchNumber(el.value).replace('.',',')});el.addEventListener('blur',()=>{el.value=formatFrenchNumber(el.value,decimals)});el.addEventListener('input',()=>{el.value=el.value.replace(/[^0-9, .\u00a0\u202f]/g,'')})}
function saveVisit(){if(!S.machine)return toast('Aucun matériel sélectionné.');let tech=$('#tech').value.trim(),techPhone=$('#techPhone').value.trim();if(!tech)return toast('Renseigne le contrôleur.');saveController(tech,techPhone);let checks=CHECKS.map((label,i)=>({label,status:$$('.checkStatus')[i].value,comment:$$('.checkComment')[i].value.trim()}));let all=visits();all.unshift({id:uid(),createdAt:new Date().toISOString(),visitDate:$('#visitDate').value,technician:tech,technicianPhone:techPhone,visitType:$('#visitType').value,globalStatus:$('#globalStatus').value,carrierKm:parseFrenchNumber($('#carrierKm').value),carrierHours:parseFrenchNumber($('#carrierHours').value),upperHours:parseFrenchNumber($('#upperHours').value),notes:$('#notes').value.trim(),checks,status:'Enregistrée',machineSnapshot:{...S.machine}});put(all);toast('Visite enregistrée.');screen('machine')}
function historyHtml(v){let cls=v.globalStatus==='Conforme'?'status-ok':v.globalStatus==='Non conforme'?'status-bad':'status-warn';return`<div class="history-item" data-id="${esc(v.id)}"><strong>${esc(v.machineSnapshot.parkNumber)} — ${esc(v.visitType)}</strong><br><span>${fmt(v.visitDate)} · ${esc(v.technician)}</span><br><span class="${cls}">${esc(v.globalStatus||v.status)}</span>${v.notes?`<div class="meta">${esc(v.notes)}</div>`:''}<div class="history-actions"><button class="btn secondary mini details">Détails</button><button class="btn danger mini delete">Supprimer</button></div><div class="detailsBox hidden"></div></div>`}
function bindHistoryActions(root){root.querySelectorAll('.history-item').forEach(el=>{let id=el.dataset.id;el.querySelector('.delete').onclick=()=>{if(confirm('Supprimer cette visite ?')){put(visits().filter(v=>v.id!==id));renderAllHistory();renderMachineHistory();toast('Visite supprimée.')}};el.querySelector('.details').onclick=()=>{let v=visits().find(v=>v.id===id),b=el.querySelector('.detailsBox');b.classList.toggle('hidden');b.innerHTML=`<div class="summary" style="margin-top:10px"><strong>Contrôleur :</strong> ${esc(v.technician||'Non renseigné')}${v.technicianPhone?` — <a class="contact-link" href="tel:${esc(v.technicianPhone.replace(/\s+/g,''))}">${esc(v.technicianPhone)}</a>`:''}<br><strong>Kilomètres porteur :</strong> ${esc(v.carrierKm?Number(v.carrierKm).toLocaleString('fr-FR')+' km':(v.meter||'Non renseigné'))}<br><strong>Heures porteur :</strong> ${esc(v.carrierHours?formatFrenchNumber(v.carrierHours,true)+' h':'Non renseigné')}<br><strong>Heures tourelle :</strong> ${esc(v.upperHours?formatFrenchNumber(v.upperHours,true)+' h':'Non renseigné')}<br><strong>Observations :</strong> ${esc(v.notes||'Aucune')}<hr>${(v.checks||[]).map(c=>`<div><strong>${esc(c.label)}</strong> : ${esc(c.status)}${c.comment?' — '+esc(c.comment):''}</div>`).join('')}</div>`}})}
function renderAllHistory(){let q=norm($('#historyFilter').value),all=visits().filter(v=>!q||norm([v.machineSnapshot.parkNumber,v.machineSnapshot.company,v.machineSnapshot.agency,v.technician,v.visitType,v.globalStatus].join(' ')).includes(q));$('#historyCount').textContent=all.length+' visite(s)';$('#allHistory').innerHTML=all.length?all.map(historyHtml).join(''):'<div class="empty">Aucune visite enregistrée.</div>';bindHistoryActions($('#allHistory'))}
function exportJson(){let blob=new Blob([JSON.stringify(visits(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='FOSELEV_VFG_visites_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2500)}
$('#q').oninput=renderResults;$('#company').onchange=()=>{agencies();renderResults()};$('#agency').onchange=renderResults;$$('.cat').forEach(x=>x.onchange=renderResults);$$('[data-go]').forEach(x=>x.onclick=()=>screen(x.dataset.go));$$('[data-nav]').forEach(x=>x.onclick=()=>screen(x.dataset.nav));$('#newVisit').onclick=startVisit;$('#saveVisit').onclick=saveVisit;$('#tech').addEventListener('input',autofillController);$('#tech').addEventListener('change',autofillController);bindNumberField('#carrierKm',false);bindNumberField('#carrierHours',true);bindNumberField('#upperHours',true);$('#historyFilter').oninput=renderAllHistory;$('#exportJson').onclick=exportJson;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.deferred=e;$('#install').classList.remove('hidden')});$('#install').onclick=async()=>{if(S.deferred){S.deferred.prompt();await S.deferred.userChoice;S.deferred=null;$('#install').classList.add('hidden')}};if('serviceWorker'in navigator&&location.protocol!=='file:')addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));fill();renderControllerSuggestions();renderResults();renderAllHistory();
})();
